<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DhfSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('dhfs')->insert([
            [
                'noReg' => 'RG03299949',
                'nama' => 'FAJAR HAQQY ASHBAHANIE',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '01-05-1999',
                'diagnosa' => 'Batuk',
                'penyakit_utama' => 'Batuk',
                'penyakit_penyerta' => null,
                'komplikasi' => null,
                'tindakan' => '1:-, 2:Dietary Counseling and Surveillance',
                'berat_badan' => '60',
                'tinggi_badan' => '165',
                'tanggal_masuk' => '26-03-2024',
                'tanggal_keluar' => '28-03-2024',
                'kode_icd' => '6:Z71.3',
                'jam_masuk' => '09:02:31',
                'jam_keluar' => '14:36:19',
                'lama_rawat' => '2 Hari',
                'rencana_rawat' => 'Ya',
                'rawat_kelas' => 'A',
                'rujukan' => null,
                'hari_penyakit' => '1',
                'asesment_igd' => '1',
                'asesment_spesialis' => '1',
                'asesment_perawat' => '1',
                'lab_darah' => '1',
                'lab_NS' => '1',
                'lab_DBT' => '1',
                'lab_ur' => '1',
                'radio_thorax' => '1',
                'radio_USG' => '1',
                'konsultasi' => '1',
                'ases_DPJP' => '1',
                'ases_nonDPJP' => '1',
                'ases_PPJ' => '1',
                'ases_gizi' => '1',
                'ases_resep' => '1',
                'ases_obat' => '1',
                'diagnosa_medis' => '1',
                'diagnosa_akut' => '1',
                'diagnosa_hiper' => '1',
                'diagnosa_mual' => '1',
                'diagnosa_cairan' => '1',
                'diagnosa_gizi' => '1',
                'displan_aktiv' => '1',
                'displan_terapi' => '1',
                'displan_diet' => '1',
                'displan_dengue' => '1',
                'edukasi_diagnosis' => '1',
                'edukasi_terapi' => '1',
                'edukasi_consent' => '1',
                'edukasi_gizi' => '1',
                'edukasi_hipertermia' => '1',
                'edukasi_nyeri' => '1',
                'edukasi_cairan' => '1',
                'edukasi_hidup' => '1',
                'edukasi_info' => '1',
                'edukasi_konseling' => '1',
                'lembar_edukasi' => '1',
                'injeksi_parasetamol' => '1',
                'injeksi_ranitidin' => '1',
                'injeksi_NaCl' => '1',
                'injeksi_koloid' => '1',
                'oral_paracetamol' => '1',
                'oral_varian' => '1',
                'transfusi' => '1',
                'intervensi_medika' => '1',
                'intervensi_nyeri' => '1',
                'intervensi_demam' => '1',
                'intervensi_cairan' => '1',
                'intervensi_infus' => '1',
                'intervensi_tetp' => '1',
                'intervensi_dpjp' => '1',
                'monev_dpjp' => '1',
                'monev_perdarahan' => '1',
                'monev_vital' => '1',
                'monev_hidrasi' => '1',
                'monev_lab' => '1',
                'monev_nyeri' => '1',
                'monev_nutrisi' => '1',
                'monev_makanan' => '1',
                'monev_antropometri' => '1',
                'monev_interaksi' => '1',
                'monev_efek' => '1',
                'monev_terapi' => '1',
                'mob_medis' => '1',
                'mob_keperawatan' => '1',
                'mob_fisio' => '1',
                'hasil_demam' => '1',
                'hasil_trombosit' => '1',
                'hasil_nyeri' => '1',
                'hasil_hipertermi' => '1',
                'hasil_komplikasi' => '1',
                'hasil_vital' => '1',
                'hasil_mual' => '1',
                'hasil_asupan' => '1',
                'hasil_status' => '1',
                'hasil_terapi' => '1',
                'hasil_obat' => '1',
                'pulang_normal' => '1',
                'pulang_NOC' => '1',
                'pulang_varian' => '1',
                'rencana_resume' => '1',
                'rencana_penjelasan' => '1',
                'rencana_surat' => '1',
                'tanggal_laporan' => '08-04-2024',
                'ttd_dokter' => null,
                'nama_dokter' => null,
                'ttd_perawat' => null,
                'nama_perawat' => null,
                'ttd_pelaksana' => null,
                'nama_pelaksana' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
