<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DiareSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('diares')->insert([
            [
                'noReg' => 'RG03299949',
                'nama' => 'FAJAR HAQQY ASHBAHANIE',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '01-05-1999',
                'diagnosa' => 'Batuk',
                'penyakit_utama' => 'Batuk',
                'penyakit_penyerta' => null,
                'komplikasi' => null,
                'tindakan' => '1:-, 2:Dietary Counseling and Surveillance',
                'berat_badan' => '60',
                'tinggi_badan' => '165',
                'tanggal_masuk' => '26-03-2024',
                'tanggal_keluar' => '28-03-2024',
                'kode_icd' => '6:Z71.3',
                'jam_masuk' => '09:02:31',
                'jam_keluar' => '14:36:19',
                'lama_rawat' => '2 Hari',
                'rencana_rawat' => 'Ya',
                'rawat_kelas' => 'A',
                'rujukan' => '-',
                'hari_penyakit' => '1',
                'asesment_igd' => '1',
                'asesment_spesialis' => '1',
                'asesment_perawat' => '1',
                'lab_darah' => '1',
                'lab_feses' => '1',
                'lab_GDS' => '1',
                'lab_varian' => '1',
                'radiologi' => '1',
                'konsultasi' => '1',
                'ases_DPJP' => '1',
                'ases_nonDPJP' => '1',
                'ases_PPJ' => '1',
                'ases_gizi' => '1',
                'ases_resep' => '1',
                'ases_obat' => '1',
                'diagnosa_medis' => '1',
                'diagnosa_diare' => '1',
                'diagnosa_cairan' => '1',
                'diagnosa_elektrolit' => '1',
                'diagnosa_nutrisi' => '1',
                'diagnosa_akut' => '1',
                'diagnosa_hiper' => '1',
                'diagnosa_kulit' => '1',
                'diagnosa_gizi' => '1',
                'displan_rumah' => '1',
                'displan_terapi' => '1',
                'displan_hygiene' => '1',
                'edukasi_diagnosis' => '1',
                'edukasi_terapi' => '1',
                'edukasi_consent' => '1',
                'edukasi_gizi' => '1',
                'edukasi_hygiene' => '1',
                'edukasi_makanan' => '1',
                'edukasi_perianal' => '1',
                'edukasi_info' => '1',
                'edukasi_konseling' => '1',
                'lembar_edukasi' => '1',
                'injeksi_ceftriaxon' => '1',
                'injeksi_Parasetamol' => '1',
                'injeksi_NaCl' => '1',
                'oral_dompridon' => '1',
                'oral_zinc' => '1',
                'rehidrasi_oral' => '1',
                'intervensi_medika' => '1',
                'intervensi_cairan' => '1',
                'intervensi_diare' => '1',
                'intervensi_elektrolit' => '1',
                'intervensi_demam' => '1',
                'intervensi_nutrisi' => '1',
                'intervensi_nyeri' => '1',
                'intervensi_kulit' => '1',
                'intervensi_resusitasi' => '1',
                'intervensi_infus' => '1',
                'intervensi_ASI' => '1',
                'intervensi_dpjp' => '1',
                'monev_dpjp' => '1',
                'monev_intake' => '1',
                'monev_vital' => '1',
                'monev_hidrasi' => '1',
                'monev_kendali' => '1',
                'monev_eliminasi' => '1',
                'monev_kulit' => '1',
                'monev_makanan' => '1',
                'monev_antropometri' => '1',
                'monev_interaksi' => '1',
                'monev_efek' => '1',
                'monev_terapi' => '1',
                'mob_medis' => '1',
                'mob_keperawatan' => '1',
                'mob_fisio' => '1',
                'hasil_diare' => '1',
                'hasil_dehidrasi' => '1',
                'hasil_seimbang' => '1',
                'hasil_komplikasi' => '1',
                'hasil_vital' => '1',
                'hasil_asupan' => '1',
                'hasil_status' => '1',
                'hasil_terapi' => '1',
                'hasil_obat' => '1',
                'pulang_normal' => '1',
                'pulang_NOC' => '1',
                'pulang_varian' => '1',
                'rencana_resume' => '1',
                'rencana_penjelasan' => '1',
                'rencana_surat' => '1',
                'tanggal_laporan' => '1',
                'nama_dokter' => '1',
                'ttd_dokter' => '1',
                'nama_perawat' => '1',
                'ttd_perawat' => '1',
                'nama_pelaksana' => '1',
                'ttd_pelaksana' => '1',
                'tanggal_laporan' => null,
                'nama_dokter' => null,
                'ttd_dokter' => null,
                'nama_perawat' => null,
                'ttd_perawat' => null,
                'nama_pelaksana' => null,
                'ttd_pelaksana' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
