<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class HemodialisisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('hemodialises')->insert([
            'noReg' => 'RG03299949',
            'nama' => 'FAJAR HAQQY ASHBAHANIE',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '01-05-1999',
            'diagnosa' => 'Batuk',
            'penyakit_utama' => 'Batuk',
            'penyakit_penyerta' => '-',
            'komplikasi' => '-',
            'tindakan' => '1:-, 2:Dietary Counseling and Surveillance',
            'berat_badan' => '60',
            'tinggi_badan' => '165',
            'tanggal_masuk' => '26-03-2024',
            'tanggal_keluar' => '28-03-2024',
            'kode_icd' => 'A15.0 - A16.0',
            'jam_masuk' => '09:02:31',
            'jam_keluar' => '14:36:19',
            'lama_rawat' => '2 Hari',
            'rencana_rawat' => 'Ya',
            'rawat_kelas' => 'A',
            'rujukan' => '-',
            'hari_penyakit' => '1',
            'asesment_igd' => '1',
            'asesment_spesialis' => '1',
            'asesment_primer' => '1',
            'lab_darah' => '1',
            'lab_elektrolit' => '1',
            'lab_ureum' => '1',
            'lab_hcv' => '1',
            'lab_pt' => '1',
            'lab_magnesium' => '1',
            'lab_tibc' => '1',
            'lab_pth' => '1',
            'radio_foto' => '1',
            'var_ekg' => '1',
            'var_echo' => '1',
            'konsultasi' => '1',
            'ases_DPJP' => '1',
            'ases_nonDPJP' => '1',
            'ases_PPJ' => '1',
            'ases_gizi' => '1',
            'ases_resep' => '1',
            'ases_obat' => '1',
            'diagnosa_aki' => '1',
            'diagnosa_end' => '1',
            'diagnosa_napas' => '1',
            'diagnosa_perfusi' => '1',
            'diagnosa_hipervolemia' => '1',
            'diagnosa_nutrisi' => '1',
            'diagnosa_nausea' => '1',
            'diagnosa_aktivitas' => '1',
            'diagnosa_kulit' => '1',
            'diagnosa_jantung' => '1',
            'diagnosa_perifer' => '1',
            'diagnosa_infeksi' => '1',
            'diagnosa_cairan' => '1',
            'diagnosa_garam' => '1',
            'diagnosa_protein' => '1',
            'displan_edukasi' => '1',
            'displan_rencana' => '1',
            'displan_obat' => '1',
            'displan_kontrol' => '1',
            'edukasi_diagnosis' => '1',
            'edukasi_terapi' => '1',
            'edukasi_consent' => '1',
            'edukasi_gizi' => '1',
            'edukasi_ginjal' => '1',
            'edukasi_hemodialisa' => '1',
            'edukasi_cdl' => '1',
            'edukasi_output' => '1',
            'edukasi_dukungan' => '1',
            'edukasi_info' => '1',
            'edukasi_konseling' => '1',
            'lembar_edukasi' => '1',
            'tindakan_cartheter' => '1',
            'tindakan_nasal' => '1',
            'injeksi_kristaloid' => '1',
            'inject_antikoagulan' => '1',
            'inject_bolus' => '1',
            'inject_heparin' => '1',
            'inject_eritropoetin' => '1',
            'oral_asamFolat' => '1',
            'oral_hipertensi' => '1',
            'intervensi_medika' => '1',
            'intervensi_elektrolit' => '1',
            'intervensi_hipertermia' => '1',
            'intervensi_infeksi' => '1',
            'intervensi_nutrisi' => '1',
            'intervensi_ADL' => '1',
            'intervensi_infus' => '1',
            'intervensi_obat' => '1',
            'intervensi_gizi' => '1',
            'intervensi_dpjp' => '1',
            'monev_dpjp' => '1',
            'monev_vital' => '1',
            'monev_cairan' => '1',
            'monev_nutrisi' => '1',
            'monev_nyeri' => '1',
            'monev_infeksi' => '1',
            'monev_makanan' => '1',
            'monev_antropometri' => '1',
            'monev_biokimia' => '1',
            'monev_fisik' => '1',
            'monev_efektiv' => '1',
            'monev_interaksi' => '1',
            'monev_efek' => '1',
            'mob_medis' => '1',
            'mob_keperawatan' => '1',
            'mob_fisio' => '1',
            'hasil_batuk' => '1',
            'hasil_lab' => '1',
            'hasil_vital' => '1',
            'hasil_Seimbang' => '1',
            'hasil_infeksi' => '1',
            'hasil_asupan' => '1',
            'hasil_status' => '1',
            'hasil_terapi' => '1',
            'hasil_rasional' => '1',
            'pulang_umum' => '1',
            'pulang_khusus' => '1',
            'rencana_resume' => '1',
            'rencana_penjelasan' => '1',
            'rencana_surat' => '1',
            'varian_rencana' => '1',
            'tanggal_laporan' => '06-04-2024',
            'nama_dokter' => NULL,
            'ttd_dokter' => NULL,
            'nama_perawat' => NULL,
            'ttd_perawat' => NULL,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
}
