<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KatarakSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('kataraks')->insert([
            'table' => 'Katarak',
            'id' => 1,
            'noReg' => 'RG03299949',
            'nama' => 'FAJAR HAQQY ASHBAHANIE',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '01-05-1999',
            'diagnosa' => 'Batuk',
            'penyakit_utama' => 'Batuk',
            'penyakit_penyerta' => '-',
            'komplikasi' => '-',
            'tindakan' => '1:-, 2:Dietary Counseling and Surveillance',
            'berat_badan' => '60',
            'tinggi_badan' => '165',
            'tanggal_masuk' => '26-03-2024',
            'tanggal_keluar' => '28-03-2024',
            'kode_icd' => '6:Z71.3',
            'jam_masuk' => '09:02:31',
            'jam_keluar' => '14:36:19',
            'lama_rawat' => '2 Hari',
            'rencana_rawat' => 'Ya',
            'rawat_kelas' => '1',
            'rujukan' => '-',
            'hari_penyakit' => '1',
            'asesment_mata' => 'Pasien masuk melalui poli, DPJP

Dilakukan pemeriksaan Visus, slit lamp, tekanan bola mata, funduskopi, retinometri (bila VISUS >= 1/60, Biometri)',
            'catatan_asesDokMata' => '1',
            'asesment_internis' => 'Atas Indikasi (pre-operasi)',
            'catatan_asesDokInternis' => '1',
            'asesment_anestesi' => 'Bila Anastesi Umum',
            'catatan_asesDokAnsestesi' => '1',
            'asesment_perawat' => 'Dilanjutkan dengan asesmen bio, psiko, sosial, spiritual, dan budaya',
            'catatan_asesPer' => '1',
            'lab_darah' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias, doloremque!',
            'catatan_labDar' => '1',
            'lab_UR' => 'Bila Anestesi Umum / atas indikasi',
            'catatan_labUR' => '1',
            'radio_thorax' => 'Bila Anestesi Umum / atas indikasi (usia > 40 tahun)',
            'catatan_radTho' => '1',
            'radio_USG' => 'Atas indikasi',
            'catatan_radUSG' => '1',
            'ekg' => 'Visit harian/Follow up',
            'catatan_ekg' => '1',
            'ases_DPJP' => 'Atas Indikasi/Emergency',
            'catatan_asesDPJP' => '1',
            'ases_nonDPJP' => 'Pendaftaran ke OK

Administrasi

Dilakukan dalam 3 shift',
            'catatan_asesNonDPJP' => '1',
            'ases_PPJ' => 'Lihat risiko malnutrisi melalui skrining gizi dan mengkaji data antropometri, biokimia, fisik/klinis, riwayat makan termasuk alergi makanan serta riwayat personal. Asesmen dilakukan dalam waktu 48 jam',
            'catatan_asesPPJ' => '1',
            'ases_gizi' => 'Dilanjutkan dengan intervensi farmasi yang sesuai hasil Telaah dan Rekonsiliasi obat',
            'catatan_asesGizi' => '1',
            'ases_resep' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias, doloremque!',
            'catatan_asesResep' => '1',
            'ases_obat' => '1',
            'diagnosa_medis' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias, doloremque!',
            'catatan_diagMedis' => '1',
            'diagnosa_akut' => 'Masalah keperawatan yang dijumpai setiap hari. Dibuat oleh perawat penanggung jawab.',
            'catatan_diagAkut' => '1',
            'diagnosa_hiper' => '1',
            'diagnosa_mual' => '1',
            'diagnosa_gizi' => '1',
            'catatan_diagGizi' => 'Sesuai dengan data asesmen, kemungkinan saja ada diagnosis lain atau diagnosis berubah selama perawatan.',
            'displan_aktiv' => '1',
            'catatan_disPlanAk' => 'Program pendidikan pasien dan keluarga (diisi 3x24 jam)',
            'displan_terapi' => '1',
            'displan_diet' => '1',
            'displan_istirahat' => '1',
            'edukasi_diagnosis' => 'Oleh semua pemberi asuhan berdasarkan kebutuhan dan juga berdasarkan Discharge Planning

Pengisian formulir informasi dan edukasi terintegrasi oleh pasien dan atau keluarga

Edukasi gizi dapat dilakukan saat awal masuk pada hari 1 atau hari ke 2

Meningkatkan kepatuhan pasien meminum/menggunakan obat

Di DTT Keluarga/Pasien',
            'catatan_emedDiag' => '1',
            'edukasi_terapi' => '1',
            'edukasi_consent' => '1',
            'edukasi_gizi' => '1',
            'catatan_egiz' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias, doloremque!',
            'edukasi_ADL' => '1',
            'catatan_ekepADL' => '1',
            'edukasi_nyeri' => '1',
            'edukasi_infeksi' => '1',
            'edukasi_diet' => '1',
            'edukasi_mual' => '1',
            'edukasi_info' => '1',
            'catatan_efarmInf' => '1',
            'edukasi_konseling' => '1',
            'lembar_edukasi' => '1',
            'catatan_lemEdTer' => '1',
            'injeksi_ranitidine' => '1',
            'catatan_injectRani' => '1',
            'injeksi_ondansentron' => '1',
            'catatan_injectOndan' => '1',
            'injeksi_kolf' => '1',
            'catatan_infusKolf' => '1',
            'oral_mefenamat' => '1',
            'catatan_oralMefe' => '1',
            'oral_ciprofloxacin' => '1',
            'catatan_oralCipro' => '1',
            'lokal_levofloxacin' => '1',
            'catatan_lokalLevo' => '1',
            'local_antibiotika' => '1',
            'catatan_lokalAnti' => '1',
            'intervensi_ECCE' => '1',
            'catatan_tatmedECCE' => '1',
            'intervensi_nyeri' => '1',
            'catatan_tatkepNyeri' => '1',
            'intervensi_terapi' => '1',
            'intervensi_demam' => '1',
            'intervensi_cairan' => '1',
            'intervensi_kontrol' => '1',
            'intervensi_infus' => '1',
            'intervensi_medikasi' => '1',
            'intervensi_operasi' => '1',
            'intervensi_luka' => '1',
            'intervensi_diet' => '1',
            'catatan_tatgiziDiet' => '1',
            'intervensi_dpjp' => '1',
            'catatan_tatfarmDPJP' => '1',
            'monev_operasi' => 'Sesuai indikasi',
            'catatan_monevOperasi' => '1',
            'monev_periksa' => 'Sesuai dengan hasil monitoring',
            'monev_komplikasi' => '1',
            'monev_perawatan' => 'Monitor Perkembangan Pasien',
            'monev_skala' => '1',
            'catatan_monevkepSkala' => '1',
            'monev_vital' => '1',
            'monev_hidrasi' => '1',
            'monev_makanan' => '1',
            'catatan_monevgiziMakanan' => '1',
            'monev_antropometri' => 'Mengacu pada NOC',
            'monev_interaksi' => '1',
            'catatan_monevfarmInteraksi' => '1',
            'monev_efek' => '1',
            'monev_terapi' => '1',
            'mob_medis' => '1',
            'catatan_mobmed' => '1',
            'mob_keperawatan' => '1',
            'mob_fisio' => '1',
            'hasil_visus' => 'Status Gizi berdasarkan antropometri, biokimia, fisik/klinis',
            'catatan_hasmedVisus' => '1',
            'hasil_nyeri' => '1',
            'catatan_haskepNyeri' => '1',
            'hasil_infeksi' => 'Meningkatkan kualitas hidup pasien',
            'hasil_respon' => '1',
            'hasil_vital' => '1',
            'hasil_asupan' => '1',
            'catatan_hasgiziAsupan' => '1',
            'hasil_status' => '1',
            'hasil_terapi' => '1',
            'catatan_hasfarmInd' => '1',
            'hasil_obat' => '1',
            'pulang_normal' => 'Varian',
            'catatan_pulangNormal' => '1',
            'pulang_NOC' => '1',
            'pulang_varian' => 'Pasien membawa Resume Perawatan/Surat Rujukan/Surat Kontrol/Homecare saat pulang',
            'catatan_pulangVarian' => '1',
            'rencana_perawatan' => '1',
            'catatan_rencanaPerawatan' => '1',
            'rencana_penjelasan' => '1',
            'rencana_kontrol' => '1',
            'tanggal_laporan' => '12-04-2024',
            'nama_dokter' => null,
            'ttd_dokter' => null,
            'nama_perawat' => null,
            'ttd_perawat' => null,
            'nama_pelaksana' => null,
            'ttd_pelaksana' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
}
