<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KemoterapiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('kemoterapis')->insert([
            'table' => 'Kemoterapi',
            'id' => 1,
            'noReg' => 'RG03299949',
            'nama' => 'FAJAR HAQQY ASHBAHANIE',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '1999-05-01',
            'diagnosa' => 'Batuk',
            'penyakit_utama' => 'Batuk',
            'penyakit_penyerta' => null,
            'komplikasi' => null,
            'tindakan' => '1:-, 2:Dietary Counseling and Surveillance',
            'berat_badan' => 60,
            'tinggi_badan' => 165,
            'tanggal_masuk' => '2024-03-26',
            'tanggal_keluar' => '2024-03-28',
            'kode_icd' => '6:A15.0 - A16.0',
            'jam_masuk' => '09:02:31',
            'jam_keluar' => '14:36:19',
            'lama_rawat' => '2 Hari',
            'rencana_rawat' => 'Ya',
            'rawat_kelas' => 'A',
            'rujukan' => null,
            'hari_penyakit' => '1',
            'asesment_igd' => '1',
            'asesment_spesialis' => '1',
            'asesment_primer' => '1',
            'lab_darah' => '1',
            'lab_elektrolit' => '1',
            'lab_ureum' => '1',
            'radio_foto' => '1',
            'radio_USG' => '1',
            'varian_pato' => '1',
            'varian_ekg' => '1',
            'konsultasi' => '1',
            'ases_DPJP' => '1',
            'ases_nonDPJP' => '1',
            'ases_PPJ' => '1',
            'ases_gizi' => '1',
            'ases_resep' => '1',
            'ases_obat' => '1',
            'diagnosa_medis' => '1',
            'diagnosa_nausea' => '1',
            'diagnosa_gangguan' => '1',
            'diagnosa_ansietas' => '1',
            'diagnosa_nyeri' => '1',
            'diagnosa_intoleransi' => '1',
            'diagnosa_adekuat' => '1',
            'diagnosa_malnutrisi' => '1',
            'displan_kondisi' => '1',
            'displan_kemoterapi' => '1',
            'displan_obat' => '1',
            'displan_tatalaksana' => '1',
            'edukasi_diagnosis' => '1',
            'edukasi_terapi' => '1',
            'edukasi_consent' => '1',
            'edukasi_gizi' => '1',
            'edukasi_keluarga' => '1',
            'edukasi_info' => '1',
            'edukasi_konseling' => '1',
            'lembar_edukasi' => '1',
            'tindakan_prekemo' => '1',
            'tindakan_kemp' => '1',
            'tindakan_postkemo' => '1',
            'terapi_omeprazole' => '1',
            'terapi_curcuma' => '1',
            'terapi_ondansetron' => '1',
            'intervensi_medika' => '1',
            'intervensi_nyeri' => '1',
            'intervensi_energi' => '1',
            'intervensi_mual' => '1',
            'intervensi_ansietas' => '1',
            'intervensi_citra' => '1',
            'intervensi_gizi' => '1',
            'intervensi_dpjp' => '1',
            'monev_dpjp' => '1',
            'monev_vital' => '1',
            'monev_mual' => '1',
            'monev_nutrisi' => '1',
            'monev_nyeri' => '1',
            'monev_ADL' => '1',
            'monev_makanan' => '1',
            'monev_antropometri' => '1',
            'monev_efektiv' => '1',
            'monev_interaksi' => '1',
            'monev_efek' => '1',
            'mob_medis' => '1',
            'mob_keperawatan' => '1',
            'mob_fisio' => '1',
            'hasil_medis' => '1',
            'hasil_vital' => '1',
            'hasil_mual' => '1',
            'hasil_nyeri' => '1',
            'hasil_asupan' => '1',
            'hasil_status' => '1',
            'hasil_terapi' => '1',
            'hasil_rasional' => '1',
            'pulang_umum' => '1',
            'pulang_khusus' => '1',
            'rencana_resume' => '1',
            'rencana_penjelasan' => '1',
            'rencana_surat' => '1',
            'tanggal_laporan' => null,
            'nama_dokter' => null,
            'ttd_dokter' => null,
            'nama_perawat' => null,
            'ttd_perawat' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
}
